# -*- coding: utf-8 -*-
"""task 1,2,3,4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fUYgL5fuoR6eYxP0w1eNiwZuPeesrM6E

# Task 1) go through some of the other in built functions

### string functions
"""

# 1)casefold()
a = "welcome to my world"
print(a.casefold())

# 2) capitalize()
b = "my name is pk"
print(b.capitalize())

# 3) count()
car ="i love buggati and buggati is fastest car "
print(car.count("buggati"))

# 4) endswith()
print(b.endswith("pk"))

#5) expandtabs()
t = "h\te\tl\tl\to"
print(t.expandtabs())

# 6)find()
x = "wellcome to my world"
print(x.find("t"))

# 7) format()
x1 = 15
y1 = 500
print ("for {} Rs i bought {} oranges".format(y1,x1))

# 8)index()
r1 = "i like riding"
print(r1.index("i"))

# 9)isalnum()
x1 = "pk772663"
print(x1.isalnum())

# 10)isalpha()
x2 = "maserati"
print(x2.isalpha())

# 11)islower()
p1 = "MY WORLD IS TOO HIGH"
print(p1.islower())

# 12)isupper()
p2 = "MY NAME IS PK"
print(p2.isupper())

# 13) replace()
p3 = "i like cricket"
print(p3.replace("cricket","tennis"))

# 14)isspace()
p1 = "      "
p2 = "   pk  "
print(p1.isspace())
print(p2.isspace())

# 15)lower()
r1 = "PARAM"
print(r1.lower())

# 16)upper()
r2 = "i love my nation"
print(r2.upper())

# 17)count()
e2 ="lion is the national animal"
print(e2.count("the"))

# 18)ljust()
l = "lion"
print(l.ljust(10),"is the king of forest")

# 19)partition()
p1 = "i play cricket sunday only"
print(p1.partition("i play"))
print(p1.partition("cricket sunday only"))

# 20)rfind()
r1 = "hello my name is unknown"
print(r1.rfind("is"))

# 21)rindex()
j1 = "searching for a new world"
print(j1.rindex("new"))

# 22)zfill()
z = "mitsubushi"
print(z.zfill(15))

# list function

# 23)append()
r1 = ["ram","kiran",500,1,2]
r1.append("param")
print(r1)

# 24)clear()

r1.clear()
print(r1)

#25)copy()

r1.copy()
print(r1)

# 26)extend()
car = ["benz","bmw","maruti","kia"]
fruit = ["mango","grapes","kiwi","orange"]
car.extend(fruit)
print(car)

# 27)insert()
r1 = [1,2,3,6,8]
r1.insert(5,22)
print(r1)

# 28)pop()
r1.pop(2)
print(r1)

# 29)remove()
r3 = [2,4,6,8,10,44,56]
r3.remove(44)
print(r3)

# 30)reverse()
r3.reverse()
print(r3)

# 31)sort()
r3.sort()
print(r3)

# dictionary function

# 32)clear()
r1 = {"king":24,"queen":30,"raj":43,}
r1.clear()
print(r1)

# 33)get()
r4 = {"car":"mustang","bike":"ducati","fruit":"orange"}
print(r4.get("bike"))

# 34)keys()
print(r4.keys())

# 35)add()
p1 ={"ram","raj","kishan"}
p1.add("param")
print(p1)

"""# Task 2"""

# check if "to" is present in "welcome to python"

str1 = "Welcome to python"
"to" in str1



"""# Task 4"""

# add item 70 after 60 in the following python list
# input
l1 = [10,20,[30,40,[50,60],80],90,100]
l1[2][2].append(70)
print(l1)

#add sublist [7,8]
#input
l2 = [1,2,[3,4,5,6],9]
l2[2].append([7,8])
print(l2)

