# -*- coding: utf-8 -*-
"""Task 5,6,7.3 ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRmbC7pYmeBk5q2YsDJ0HhkGgeCIwEdq

####Task 5
"""

# task 5 from the given dictionary do the following tasks
# 1) access "Mike"
# 2) access 80
# 3) change "mike" to "your name" 
# 4) add ML = 80 and DL = 80 inside marks.

dict1 = {"april_batch":{"student":{"name":"Mike","marks":{"python":80,"marks":70}}}}
dict1

# 1) access "Mike"
dict1["april_batch"]["student"]["name"]

# 2) Access 80
dict1["april_batch"]["student"]["marks"]["python"]

# 3) change "Mike"to "your name"
dict1["april_batch"]["student"]["name"] = "pramod"
print(dict1)

# 4) add ML=80 and DL=80 inside marks.
dict1["april_batch"]["student"]["marks"].update({"ML":80,"DL":80})

print(dict1)

"""##Task 6"""

# Add and remove the elements from a tuple

tup1 = (10,20,30,40,50)

"""#Step 1
convert tuple into list
"""

#adding data
l1 = list(tup1)

"""#step 2
assign the data 
"""

l1.insert(1,15)
l1.insert(3,25)
l1.insert(5,35)
l1.insert(7,45)
l1.insert(9,55)
l1.insert(10,60)
print(l1)

"""#step 3
convert list into tuple
"""

tup2=tuple(l1)
print(tup2)

type(tup2)

# Removing data

"""#step 1
convert tuple to list
"""

l2 = list(tup2)
print(l2)

"""#step 2
removing data from list
"""

l2.remove(60)
print(l2)



"""#Task 7"""

# Go through other inbuilt methods like
# 1) Difference
# 2) Symmetric_difference

# Difference
x = {"kishan","param","sanket","amar"}
y = {"sheetal","param","karan","ram"}
x.difference(y)
print(x)

# Symmetric_difference
p = {"param","amar","sanket","kishan"}
q = {"sheetal","kishan","ram","jai"}
p.difference_update(q)
print(p)



"""#Task 3"""

# Create a list of 10 data and access 5th to 8th data.

list1 = [25000,50000,75000,100000,125000,150000,175000,200000,225000,250000,275000,300000]
list1[5:8]

